Publish Package 5.2.0
etn-ccis/blui-react-native-workflows pull request #295
Opened 2023-10-26 16:01 UTC by ektaghag-eaton

Publish Package 5.2.0

#### Changes proposed in this Pull Request:

- This PR contains changes for 6.0.0-alpha.1 (Published By the Fiji team)
- Package 5.2.0 (Fixes for Fiji team)
-

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

- **For Version 6.0.0-alpha.1**

-   Ability to hide the CreatePassword screen.
-   Ability to hide the login form in the Login screen.

- For Version 5.2.0

- Disable Next button when valid prop of Account Details form is false ([#276](https://github.com/etn-ccis/blui-react-native-workflows/issues/276)).
-   Verification code prefilled value issue on Verify Email screen on resend, next and back button pressed ([#280](https://github.com/etn-ccis/blui-react-native-workflows/issues/280)).

-   Incorrect navigation on dismissal of error occurred in Account Details screen ([#275](https://github.com/etn-ccis/blui-react-native-workflows/issues/275)).

#### Any specific feedback you are looking for?

- In **5.2.0 version** changes from **6.0.0-alpha.1** will be available . @joebochill is it fine?

2023-10-26 19:02 UTC, JeffGreiner-eaton commented on login-workflow/CHANGELOG.md
> +## v6.0.0 (Unreleased)
should this be updated to be v6 with date or is this for alpha?

2023-10-27 03:29 UTC, ektaghag-eaton commented on login-workflow/CHANGELOG.md
> +## v6.0.0 (Unreleased)
V6 is still in the alpha version, we haven’t published 6.0.0.

2023-10-27 12:38 UTC, joebochill commented on login-workflow/CHANGELOG.md
> +## v6.0.0 (Unreleased)
v6 should be removed from the changelog...those changes that were part of the original 6.0.0-alpha were incorporated into 5.2.0. So there will be no unreleased changes after 5.2.0 is published.

2023-10-27 12:40 UTC, joebochill requested changes

2023-10-27 12:40 UTC, joebochill commented on login-workflow/package.json
> +        "@brightlayer-ui/react-auth-shared": "^4.0.0-alpha.2",
We cannot use pre-release versions of dependencies in a latest version of our packages.

2023-10-27 17:04 UTC, JeffGreiner-eaton commented
been trying to run start:example-ios here and getting this error on fresh clone. My local issue?

<img width="1016" alt="image" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/119693939/a4242b64-5bba-4fdd-a373-cb8e51e96638">

2023-10-27 18:37 UTC, joebochill commented
@JeffGreiner-eaton looks like maybe a local cocoapods version issue. I'm able to clone and run (once i disable hermes in the podfile).

2023-10-27 18:37 UTC, joebochill approved these changes

2023-10-27 18:47 UTC, JeffGreiner-eaton approved these changes
approving as secondary on review to get merged

2023-10-27 19:33 UTC, joebochill requested changes

2023-10-27 19:33 UTC, joebochill commented on login-workflow/package.json
>      "dependencies": {
We should avoid making dependency changes in a minor version if we can. Android currently fails to run (seems to be related to the updated version of react-native-gesture-handler).

2023-10-30 17:53 UTC, joebochill approved these changes

2023-10-31 06:29 UTC, surajeaton approved these changes

2023-10-31 07:40 UTC, merged