add header
etn-ccis/blui-react-native-workflows pull request #325
Opened 2024-01-30 10:24 UTC by ArshdeepSingh3-eaton

Fixes # .

#### Changes proposed in this Pull Request:

- Added WorkflowCardHeader component
-
-

#### Screenshots / Screen Recording (if applicable)

-
<img width="475" alt="Screenshot 2024-01-30 at 3 51 24 PM" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/144440086/cafd06d9-e662-43d4-9440-ff7538a7621e">

#### To Test:

-

#### Any specific feedback you are looking for?

-

2024-01-31 07:19 UTC, ektaghag-eaton reviewed
Header is going up in tablet view(see below image)
<img width="683" alt="Screenshot 2024-01-31 at 12 16 54 PM" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/133877691/91095870-3cd2-4d5d-a2a1-ab1263b0d63c">

Below changes are working fine
<img width="388" alt="Screenshot 2024-01-31 at 12 17 14 PM" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/133877691/04f20dd8-3204-4b8e-907e-f2b9b6446480">


<img width="389" alt="Screenshot 2024-01-31 at 12 31 16 PM" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/133877691/204b8791-af0e-4768-8b0d-f11201798666">

2024-01-31 07:19 UTC, ektaghag-eaton commented on login-workflow/src/components/WorkflowCard/WorkflowCardHeader.tsx
> +export const isLightColor = (color: string): boolean => {
Any specific reason to add this funtion?

2024-02-01 10:43 UTC, ArshdeepSingh3-eaton commented on login-workflow/src/components/WorkflowCard/WorkflowCardHeader.tsx
> +export const isLightColor = (color: string): boolean => {
to check if the background color of header is light or dark
and based on that text color of status bar is changing

2024-02-01 10:44 UTC, ArshdeepSingh3-eaton commented on login-workflow/src/components/WorkflowCard/WorkflowCardHeader.tsx
> +export const isLightColor = (color: string): boolean => {
the header is supposed to go inside workflowcard and in case of tablet 
it will be shown in the center of screen and not on the top

2024-02-01 20:45 UTC, JeffGreiner-eaton commented on login-workflow/src/components/WorkflowCard/WorkflowCardHeader.tsx
> +export const isLightColor = (color: string): boolean => {
I'm confused on this to, shouldn't the theme take care of this?

2024-02-01 20:51 UTC, JeffGreiner-eaton commented
maybe we can update the example in this PR or another one but can we use DrawerNavigationProp instead of StackNavigationProp for AppProps? it takes care of the typescript warning in the file....

import { DrawerNavigationProp } from '@react-navigation/drawer';

type AppProps = {
    navigation: DrawerNavigationProp<RootStackParamList, 'WorkFlowCardExample'>;

<WorkflowCardHeader
                        title="EATON Workflow Example"
                        ...
                        onIconPress={(): void => {
                            navigation.navigate('Home');
                        }}

2024-02-01 20:54 UTC, JeffGreiner-eaton commented
This seems ok.. but using textColor here also changes icon color by default?

<img width="282" alt="image" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/119693939/2b1663a8-2528-43c6-a219-c15807007d16">

<img width="440" alt="image" src="https://github.com/etn-ccis/blui-react-native-workflows/assets/119693939/9e2ce139-e994-4c75-8ca4-4e9c8ba42cee">

2024-02-02 15:33 UTC, JeffGreiner-eaton commented
looks good, are we able to update styles for larger devices mentioned above by @ektaghag-eaton?
Header to close to safe area...

![image](https://github.com/etn-ccis/blui-react-native-workflows/assets/119693939/fcc6b8b4-4126-446f-9861-001ff8a6ecf0)

![image](https://github.com/etn-ccis/blui-react-native-workflows/assets/119693939/79814b01-a809-4fba-ba78-62648f186370)

2024-02-05 06:48 UTC, surajeaton reviewed
Please resolve the conflicts.

2024-02-05 13:22 UTC, ektaghag-eaton requested changes
Hi @ArshdeepSingh3-eaton , can you update this with workflowCardHeader ?
https://github.com/etn-ccis/blui-react-native-workflows/blob/release/R31/login-workflow/src/components/WorkflowCard/WorkflowCard.tsx#L42

2024-02-05 13:55 UTC, ektaghag-eaton approved these changes
Working fine.

2024-02-05 13:55 UTC, merged